In [3]:
import numpy as np
arr1 = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

arr2 = np.array([[9,8,7],
              [6,5,4],
              [3,2,1]])

arr3 = np.array([[9,8,7],
              [6,5,4,2],
              [3,2,1]])

In [4]:
arr1 + arr2

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [5]:
arr1*arr2

array([[ 9, 16, 21],
       [24, 25, 24],
       [21, 16,  9]])

In [6]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
arr2

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [8]:
arr1.dot(arr2)

array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])

In [9]:
arr2.dot(arr1)

array([[ 90, 114, 138],
       [ 54,  69,  84],
       [ 18,  24,  30]])

In [12]:
arr = np.array([1,2,3,4,5])

In [16]:
arr[2:-2]

array([3])

In [27]:
arr1[ :2, : ]

array([[1, 2, 3],
       [4, 5, 6]])

## Sorting

In [29]:
arr = np.array([[7,3,6,8,4],[7,2,9,8,6],[5,4,3,2,1]])

In [30]:
arr

array([[7, 3, 6, 8, 4],
       [7, 2, 9, 8, 6],
       [5, 4, 3, 2, 1]])

In [31]:
np.sort(arr,axis = 1, kind = 'mergesort') #row-wise sort

array([[3, 4, 6, 7, 8],
       [2, 6, 7, 8, 9],
       [1, 2, 3, 4, 5]])

In [32]:
np.sort(arr, axis = 0, kind = 'heapsort') #column-wise sort

array([[5, 2, 3, 2, 1],
       [7, 3, 6, 8, 4],
       [7, 4, 9, 8, 6]])

In [33]:
np.sort(arr, kind = 'heapsort') #default = row-wise sort

array([[3, 4, 6, 7, 8],
       [2, 6, 7, 8, 9],
       [1, 2, 3, 4, 5]])

## Merging arrays

In [36]:
arr1 = np.array([[1,2,3,4],
                [5,6,7,8]])

arr2 = np.array([[8,7,6,5],
                [4,3,2,1]])

In [37]:
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [38]:
arr2

array([[8, 7, 6, 5],
       [4, 3, 2, 1]])

In [39]:
np.vstack((arr1,arr2)) #vertically stacking

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [8, 7, 6, 5],
       [4, 3, 2, 1]])

In [40]:
np.hstack((arr1,arr2)) #horizontally stacking

array([[1, 2, 3, 4, 8, 7, 6, 5],
       [5, 6, 7, 8, 4, 3, 2, 1]])

In [42]:
np.concatenate((arr1,arr2), axis = 1) #horizontally stacking

array([[1, 2, 3, 4, 8, 7, 6, 5],
       [5, 6, 7, 8, 4, 3, 2, 1]])

In [47]:
arr = np.concatenate((arr1,arr2), axis = 0) #vertically stacking

In [48]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [8, 7, 6, 5],
       [4, 3, 2, 1]])

In [46]:
np.hsplit(arr,2) # horizontal split

[array([[1, 2],
        [5, 6],
        [8, 7],
        [4, 3]]),
 array([[3, 4],
        [7, 8],
        [6, 5],
        [2, 1]])]

In [49]:
np.vsplit(arr,2) #vertical split

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[8, 7, 6, 5],
        [4, 3, 2, 1]])]

## Arrays Slicing - DAP

In [53]:
arr = np.array([1,2,3,4,5,6,7,8])

In [54]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [56]:
arr[3: ]

array([4, 5, 6, 7, 8])

In [57]:
arr[ :-3]

array([1, 2, 3, 4, 5])

In [58]:
arr= np.array([[1,2,3,4],[5,6,7,8],[8,7,6,5],[4,3,2,1]])

In [59]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [8, 7, 6, 5],
       [4, 3, 2, 1]])

In [65]:
arr[2: , : ]

array([[8, 7, 6, 5],
       [4, 3, 2, 1]])

In [67]:
arr[2 , 2]

6

## Automating using Numpy

In [68]:
lst = [1,2,3,4,5,6,7,8,9,10]

In [69]:
total =0
for i in lst:
    if(i>5):
        total +=1
print(total)

5


In [70]:
lst = np.array([1,2,3,4,5,6,7,8,9,10])

In [72]:
lst[lst > 5]

array([ 6,  7,  8,  9, 10])

In [73]:
len(lst[lst > 5])

5

In [74]:
print(lst[lst > 5])

[ 6  7  8  9 10]


In [76]:
print(lst[lst % 3 == 0])

[3 6 9]


In [77]:
arr.dtype

dtype('int32')

In [80]:
print(lst)

[array([1, 2, 3, 4]), array([5, 6, 7, 8]), array([8, 7, 6, 5]), array([4, 3, 2, 1])]


In [84]:
print(type(lst))

<class 'list'>


In [90]:
import numpy as np

array = np.full((11, 12),5)
print(array)

[[5 5 5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5 5 5]]


In [91]:
 c = np.array([6, 7, 5, 8])

d = np.array([4, 3, 7, 8])

pro = c.dot(d)  

print(pro)

144


In [94]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [8, 7, 6, 5],
       [4, 3, 2, 1]])

In [97]:
arr.transpose()

array([[1, 5, 8, 4],
       [2, 6, 7, 3],
       [3, 7, 6, 2],
       [4, 8, 5, 1]])

In [100]:
np.flipud(arr)

array([[4, 3, 2, 1],
       [8, 7, 6, 5],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [102]:
arr.size

16

In [109]:
np.sort(c)[::-1]

array([8, 7, 6, 5])

In [112]:
array_1 = [1,2,3,5,4,6,7,8,5,3,2]
print(array_1[1::2])

[2, 5, 6, 8, 3]


In [120]:
 import numpy as np

array_1 = np.array([1, 2, 3, 4])

array_2 = np.array([5, 6, 7, 8])

array_new = np.stack((array_1, array_2),axis =1)

print(array_new)

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [133]:
a = np.array([[1, 2], [3, 4]])

b = np.array([[5, 6]])

b= np.reshape(b,(2,1))
np.concatenate((a, b), axis=1)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [132]:
b

array([[5, 6]])

In [139]:
array1 = np.array([[1, 2, 3, 4, 5],[20,30,40,50,60]])

array2 = np.array([[6, 7, 8, 9, 10],[9,8,7,6,5]])

array1 = np.column_stack([array1, array2])

print(array1)

[[ 1  2  3  4  5  6  7  8  9 10]
 [20 30 40 50 60  9  8  7  6  5]]


In [136]:
array1

array([[ 1,  2,  3,  4,  5],
       [20, 30, 40, 50, 60]])

In [137]:
array2

array([[ 6,  7,  8,  9, 10],
       [ 9,  8,  7,  6,  5]])

In [140]:
print(arr[arr>5])

[6 7 8 8 7 6]
